name: muffa
version: 1.0.0+1
description: A fridge management app.

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  cloud_firestore: ^4.0.0
  google_sign_in: ^6.0.0
  shared_preferences: ^2.0.15
  image_picker: ^1.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

flutter:
  uses-material-design: true
